### ISSUE TITLE
Select as destination Storage

### ISSUE THREAD

**Issue by twonky4** [KiameV/rimworld-rimfridge#54]
Can you change this mod so I can select a fridge as destination storage in a kitchen?

**Comment by KiameV** [comment]
Due to how RW code is written this is not possible. The best work around is to use Better Workbench Management which will allow you to select fridges (iirc)
Steam: https://steamcommunity.com/sharedfiles/filedetails/?id=935982361
Direct Download: https://github.com/Falconne/ImprovedWorkbenches/releases/tag/1.2.24
